apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: |
    worker_processes 1;

    events {
        worker_connections 1024;
    }

    http {
        include       mime.types;
        default_type  application/octet-stream;

        server {
            listen 80;
            server_name localhost;

            # Serve files from the static folder where the exchange_rates.html is located
            location / {
                root /usr/share/nginx/html;
                index exchange_rates.html;
            }

            # Optionally, add other configurations, e.g., handling errors
            error_page 404 /404.html;
            location = /404.html {
                root /usr/share/nginx/html;
                internal;
            }
        }
    }
