apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange-rates-web
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exchange-rates-web
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true"
      labels:
        app: exchange-rates-web
    spec:
      serviceAccountName: ksa
      containers:
        - name: nginx
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          volumeMounts:
            - name: exchange-rates-volume
              mountPath: /usr/share/nginx/html
              readOnly: true
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
      volumes:
      - name: exchange-rates-volume
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            bucketName: api-bucket-default
            mountOptions: "implicit-dirs"
      - name: nginx-config
        configMap:
          name: nginx-config
      imagePullSecrets:
        - name: docker-credentials