name: Build-Docker-web-image
on:
  push:
    branches:
      - main
    paths:
      - www/**
      - Dockerfile
  pull_request:
    branches:
      - main
    paths:
      - www/**
      - Dockerfile
  
env:
  IMAGE_NAME: api-web
  BASE_VERSION: 0.1
  GCP_PROJECT_ID: abiding-envoy-449913-f1
  
jobs:
  build_docker:
    runs-on: ubuntu-latest   
    steps:   
      - uses: actions/checkout@v2

      - name: Set vars
        id: vars
        run: |
          tag=`git tag --points-at HEAD | sed --expression='s/^v//g' | sed --expression='s/\//-/g'`
          branch=`echo $GITHUB_REF | sed -r --expression='s/refs\/([a-z]+)\///g' | sed --expression='s/\//-/g'`
          build_version=`echo $tag  | sed --expression="s/^$/${{ env.BASE_VERSION }}.${{github.run_number}}-$branch/g"`
          echo "Version: $build_version"
          echo "BUILD_VERSION=$build_version" >> $GITHUB_ENV

      - name: Build docker image
        run: docker build -t gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{env.BUILD_VERSION}} -t gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest .

      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.API_GOOGLE_CREDENTIALS }}'
    
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
          
      - name: Push docker image
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          gcloud auth configure-docker gcr.io
          docker push gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{env.BUILD_VERSION}}
          docker push gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest

      - name: Update helm charts
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          VERSION_FILE='versions/api-web.yaml'
          echo "# This file is managed by Helm Build workflow" > $VERSION_FILE
          echo "image:" >> $VERSION_FILE
          echo "  tag: ${{env.BUILD_VERSION}}" >> $VERSION_FILE
          echo "VERSION_FILE=$VERSION_FILE" >> $GITHUB_ENV
  
      - name: Commit and push
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          git config --global user.email "api@prochazka.cc"
          git config --global user.name "Github Actions"
          git add .
          git commit -m "Publish helm version build to ${{env.BUILD_VERSION}}" || echo "No changes to commit"
          git push
        continue-on-error: true